SystemOrganization addCategory: #'ShoreLine-Web'!
SystemOrganization addCategory: 'ShoreLine-Web-Blog'!
SystemOrganization addCategory: 'ShoreLine-Web-Data'!
SystemOrganization addCategory: 'ShoreLine-Web-Pages'!
SystemOrganization addCategory: 'ShoreLine-Web-Server'!
SystemOrganization addCategory: 'ShoreLine-Web-Session'!
SystemOrganization addCategory: 'ShoreLine-Web-StackTraces'!
SystemOrganization addCategory: 'ShoreLine-Web-Widgets'!
