updating
includeLibs: anHtmlRoot

	anHtmlRoot script url: 'lib/jquery/dist/jquery.min.js'.
	
	anHtmlRoot stylesheet url: 'lib/bootstrap/dist/css/bootstrap.min.css'.
	anHtmlRoot stylesheet url: 'lib/bootstrap/dist/css/bootstrap-theme.min.css'.
	anHtmlRoot script url: 'lib/bootstrap/dist/js/bootstrap.min.js'.
	anHtmlRoot script url: 'lib/moment/min/moment.min.js'.
	anHtmlRoot javascript url: 'lib/d3/d3.min.js'.
	anHtmlRoot javascript url: 'js/test.js'.